### ISSUE TITLE
UnderstandExceptionLogger failing with empty message

### ISSUE THREAD

**Issue by mikefrancis** [understand/understand-laravel#2]
Have followed the instructions to set this up and when I run the test command:

```
\Log::info('Understand.io test');
```

We get the following:

```
Understand\UnderstandLaravel5\Exceptions\HandlerException with message 'understand-laravel: '
```

Which doesn't seem to be very useful. How can I find out what's causing the issue?

**Comment by aivis** [comment]
Hey @mikefrancis ,

1) You can try to debug response from the server here (probably it will show something helpful):
https://github.com/understand/understand-laravel5/blob/master/src/Understand/UnderstandLaravel5/Handlers/BaseHandler.php#L132

```php
    protected function handleError($responseArr, $requestData)
    {
        dd($responseArr, $requestData);
``` 

2) Make sure your input key is valid.
```
curl -XPOST https://api.understand.io/REPLACE_WITH_YOUR_INPUT_KEY -d '{"message":"my first event"}'
```


4) Otherwise please contact us via support channel http://understand.uservoice.com/ and please provide following information:
- Channel id
- Full stack trace of an exception


Thanks.
